apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: nginx-test
spec:
  secretName: cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "nginx.chengleqi.com"

